project:
  type: website
  resources:
    - "css/"
    - "js/"
    - "*.html"
  output-dir: docs

website:
  title: "hambiEvoVEnv"
  sidebar:
    style: "docked"
    background: light
    search: true
    contents:
      - section: "Community densities workflow"
        contents:
          - text: "1) Process and plot densities"
            file: R/strep_only/communities/cell_density/01_analysis.qmd
      
      - section: "Community composition workflow"
        contents:
          - text: "1) Amplicon data wrangling"
            file: R/strep_only/communities/amplicon_sp_counts/01_format_rbec_tab.qmd
          - text: "2) Community composition barplot"
            file: R/strep_only/communities/amplicon_sp_counts/02_composition_plotting.qmd
          - text: "3) Community ordination"
            file: R/strep_only/communities/amplicon_sp_counts/03_ordination_analysis.qmd
          - text: "4) Community diversity"
            file: R/strep_only/communities/amplicon_sp_counts/04_diversity.qmd
          - text: "5) Community JSD divergences"
            file: R/strep_only/communities/amplicon_sp_counts/05_JSD_analysis.qmd

      - section: "Clones workflow"
        contents:
          - text: "1) Inspect/Smooth curves"
            file: R/strep_only/monocultures/clone_phenotyping/01_growth_curve_qc.qmd
          - text: "2) Summarize curves"
            file: R/strep_only/monocultures/clone_phenotyping/02_growthrate_auc.qmd
          - text: "3) Analysis and plot"
            file: R/strep_only/monocultures/clone_phenotyping/03_growth_summary_analysis.qmd

format:
  html:
    theme:
      - cosmo
    # include table of contents
    toc: true
    # when printing dataframes use rmarkdown::paged_table())
    df-print: paged
    # set default dimensions for figures
    fig-width: 8
    fig-height: 6
    # tidy format R code upon render
    tidy: false
    # include line numbers in code blocks
    code-line-numbers: true
    # The code-link option enables hyper-linking of functions within code blocks to their online documentation:
    #code-link: true
    number-sections: true
    code-fold: show
    code-summary: "Show/hide code"
    code-tools: true
  
# auto: re-render only when source changes   
execute:
  freeze: false 
  
editor: source